sudo: required

git:
  depth: 1

services:
  - docker
  - docker-compose

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0
  matrix:
    - DRUPAL_VERSION=8.6.x
    - DRUPAL_VERSION=8.5.x
    - DRUPAL_VERSION=8.5.x-dev

before_install:
  - docker-compose build
  - docker-compose up --no-start
  - docker-compose start

install:
  # Temporarily use sudo to overcome permission issues.
  - docker-compose exec -u root node npm install --unsafe-perm
  - docker-compose exec -u root node npm run build
  - docker-compose exec -u web web composer require drupal/core:$DRUPAL_VERSION

before_script:
  - docker-compose exec -u web web ./vendor/bin/run drupal:site-setup
  - docker-compose exec -u web web ./vendor/bin/run drupal:site-install

script:
  - docker-compose exec -u web web ./vendor/bin/grumphp run
  - docker-compose exec -u web web ./vendor/bin/phpunit
  - docker-compose exec -u web web ./vendor/bin/behat

notifications:
  email: false
